name: my_app
description: A new Flutter project

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  parse_server_sdk_flutter: ^7.0.1 # ✅ Stable
  


dependency_overrides:
  idb_shim: ^2.3.4
  sembast: ^3.1.0


flutter:
  uses-material-design: true

analyzer:
  exclude:
    - "**/idb_shim/**"
    - "**/sembast/**"
